### PR TITLE
Revert "refactor: convert to less"

### PR DESCRIPTION
**Pull request by mustafa-archived**
Reverts catppuccin/twitch#5 until I take a look at the code

### CODE REVIEW

**Comment by mustafa-archived** [comment]
@isabelroses will merge it back once I confirm it's all fine, thanks again

**Comment by isabelroses** [comment]
> @isabelroses will merge it back once I confirm it's all fine, thanks again

@mustafakhalaf-git don't worry I expected for you to check it through

**Comment by mustafa-archived** [comment]
> > @isabelroses will merge it back once I confirm it's all fine, thanks again
> 
> @mustafakhalaf-git don't worry I expected for you to check it through

Wasn't on PC when I checked the PR, didn't notice there was a change to the css file until I merged it, will check through later

**Comment by mustafa-archived** [comment]
@isabelroses I would like to understand why is there no userstyle at the top of the css? from what I understood there should be a userstyle that looks like this

```/* ==UserStyle==
@name           Twitch Catppuccin
@namespace      github.com/catppuccin/userstyles/styles/twitch
@homepageURL    https://github.com/catppuccin/userstyles/tree/main/styles/twitch
@version        1.0.5
@description    Soothing pastel theme for Twitch
@author         Catppuccin - mustafakhalaf-git
@preprocessor   less
@updateURL      https://github.com/catppuccin/twitch/raw/main/catppuccin.user.css
@license        GNU-V3.0

@var select lightTheme "Light Variant" ["latte:Latte"]
@var select darkTheme "Dark Variant" ["frappe:Frappe", "macchiato:Macchiato", "mocha:Mocha"]
==/UserStyle== */

**Pull request merged**
